<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(OutDir)' != ''">
    <OutDir>$([MSBuild]::NormalizePath('$(SolutionDir)', '$(OutDir)'))</OutDir>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalOptions>/FS %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
