#include "pch.h"

#define STORAGE_POC_ENCLAVE_FAMILY_ID \
    { \
        0xAA, 0xA1, 0xB2, 0xC3, 0xDD, 0xE4, 0xF5, 0x16, \
        0x27, 0x38, 0x49, 0x5A, 0x6B, 0x7C, 0x8D, 0x9E, \
    }

#define STORAGE_POC_SNAPSHOT_IMAGE_ID \
    { \
        0x10, 0x21, 0x32, 0x43, 0x54, 0x65, 0x76, 0x87, \
        0x98, 0xA9, 0xBA, 0xCB, 0xDC, 0xED, 0xFE, 0x0F, \
    }

#define ENCLAVE_IMAGE_VERSION 0xA065F400
#define STORAGE_POC_SVN 1
#define ENCLAVE_ADDRESS_SPACE_SIZE 0x20000000

#ifndef ENCLAVE_MAX_THREADS
#define ENCLAVE_MAX_THREADS 8
#endif

extern "C" const IMAGE_ENCLAVE_CONFIG __enclave_config = {
    sizeof(IMAGE_ENCLAVE_CONFIG),
    IMAGE_ENCLAVE_MINIMUM_CONFIG_SIZE,
    IMAGE_ENCLAVE_POLICY_STRICT_MEMORY | IMAGE_ENCLAVE_POLICY_DEBUGGABLE,
    0,
    0,
    0,
    STORAGE_POC_ENCLAVE_FAMILY_ID,
    STORAGE_POC_SNAPSHOT_IMAGE_ID,
    ENCLAVE_IMAGE_VERSION,
    STORAGE_POC_SVN,
    ENCLAVE_ADDRESS_SPACE_SIZE,
    ENCLAVE_MAX_THREADS,
    IMAGE_ENCLAVE_FLAG_PRIMARY_IMAGE};

BOOL WINAPI DllMain(HINSTANCE, DWORD, LPVOID)
{
    return TRUE;
}
